### ISSUE TITLE
Problems with "transparent" types

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [semlanik/qtprotobuf#66]
The types using "transparent" wrapper break **a lot** of QML functionality: To demonstrate, I created this proto:

```
syntax = "proto3";

package test;

message Test1 {
	int32 count = 1; 
}
```

The generated class defines the property as follows:

![image](https://user-images.githubusercontent.com/16037814/72451651-415f4a80-378a-11ea-901d-f439393b2ac5.png)

I also created another class Test2 manually, using "int" as the property type:

![image](https://user-images.githubusercontent.com/16037814/72451725-5cca5580-378a-11ea-8757-75fab5ba4ce9.png)

I then registered both types with QML:

```
    // Register Qt Protobuf-generated types
    QtProtobuf::qRegisterProtobufTypes();

    qmlRegisterType<Test2>("test", 1, 0, "Test2");
```

**Problem # 1: Property assignment is broken** 

```
    property Test1 test1: Test1 {
        count: 0
    }

    property Test2 test2: Test2 {
        count: 0
    }
```

The above results in error:

qrc:/main.qml:13 Invalid property assignment: unsupported type "QtProtobuf::int32"

So, the assignment is ok for Test2 but not for Test1.

**Problem # 2: Implicit boolean conversion is broken**

I comment out the broken assignment so that both test1 and test2 have count = 0 and display the following:

```
    Row {
        Label {
            text: test1.count ? "TRUE" : "FALSE"
        }

        Label {
            text: "   "
        }

        Label {
            text: test2.count ? "TRUE" : "FALSE"
        }
    }
```

The result is:

![image](https://user-images.githubusercontent.com/16037814/72452162-175a5800-378b-11ea-8940-3775b8c57851.png)

It was expected that test1.count (being an integer equal to 0) would convert to "false" - but the opposite is the case. I guess that the implicit conversion in this case is the "null" test instead.

**Problem # 3: Locale formatting is broken**

The transparent types are not recognized as "Number" by QML. So the following code also results in unexpected output:

```
    Row {
        Label {
            text: test1.count.toLocaleString(Qt.locale())
        }

        Label {
            text: "   "
        }

        Label {
            text: test2.count.toLocaleString(Qt.locale())
        }
    }
```

Results in:

![image](https://user-images.githubusercontent.com/16037814/72452571-c860f280-378b-11ea-91ee-527da8c53b62.png)

Is there any way to make "transparent" types compatible with expected QML behavior, or to get rid of these wrappers?

**Comment by semlanik** [comment]
@R0ll1ngSt0ne, did you ```import QtProtobuf 0.1```?

If not you need make this for transparent types registration. But there is still issue (https://bugreports.qt.io/browse/QTBUG-76303) in Qt that I fixed, but not sure when exactly it will be integrated to mainline Qt.

Overall I tried to integrate more integral way for types conversion, but it was declined by Qt. So they would like to migrate to strict static typification in QML and probably in Qt6 it would be possible to make complete support of transparent types using new strict static typification concepts.

**Comment by R0ll1ngSt0ne** [comment]
P.S. Casting the transparent type property to Number solves the above issue, but this feels like a crutch - C++ to QML type conversion should recognize those types as Number by default...

        Label {
            text: Number(test1.count).toLocaleString(Qt.locale())
        }

**Comment by R0ll1ngSt0ne** [comment]
I added the import, but getting this error:

qrc:/main.qml:5 plugin cannot be loaded for module "qtprotobuf": File name case mismatch for "C:/Qt/5.13.2/msvc2017/qml/qtprotobuf/protobufquickplugind.dll"

Is the plugin included with Qt distribution, or do I need to recompile it from qtprotobuf source code?

**Comment by semlanik** [comment]
It's a part of project, so you need to compile it and place to specific qml folder. To be honest, I'm not so confident about windows build procedure.

**Comment by R0ll1ngSt0ne** [comment]
Ok, it seems that changing DLL name from "protobufquickpluginD.dll" to "protobufquickplugind.dll" somehow fixed import issue.

When I import the plugin, the assignment problem is fixed - but implicit conversion to bool and Number local formatting still do not work

**Comment by semlanik** [comment]
I have in mind idea how to make transparent type work in QML better way. Will try to provide concept next week.
